[build]
  command = "npm run build"
  publish = "build"

[build.environment]
SECRETS_SCAN_OMIT_KEYS = "REACT_APP_FIREBASE_PROJECT_ID,REACT_APP_FIREBASE_FUNCTIONS_REGION,REACT_APP_FIREBASE_MEASUREMENT_ID,REACT_APP_FIREBASE_APP_ID,REACT_APP_NEWSLETTER_ENDPOINT,REACT_APP_FIREBASE_API_KEY,REACT_APP_FIREBASE_STORAGE_BUCKET,REACT_APP_FIREBASE_MESSAGING_SENDER_ID,REACT_APP_STRIPE_PUBLISHABLE_KEY,REACT_APP_AI_ENDPOINT"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "https://australia-southeast1-deakin-app-7d1a8.cloudfunctions.net/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
